name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Import Config
        run: |
          cp -f config/EasyThreeD/ET4000PLUS/Configuration.h Marlin/Configuration.h
          cp -f config/EasyThreeD/ET4000PLUS/Configuration_adv.h Marlin/Configuration_adv.h
      - name: Build PlatformIO Project
        run: pio run -e mks_robin_lite_maple
      - name: Move firmware to config folder
        run: |
          cp .pio/build/mks_robin_lite_maple/mksLite.bin config/EasyThreeD/ET4000PLUS/

      - name: Push firmware
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add config/EasyThreeD/ET4000PLUS/mksLite.bin
          git commit -m "Compiled firmware"
          git push